---
name: 'default'
enable_udp: true      #enable udp
port : 5351
password: "ssserver-very-long-password-876410482"
method: "aes-256-cfb"
timeout: "100"
port_password: #port password dictionary
  5351 : "ssserver-very-long-password-876410482"
  5352 : "ssserver-very-long-password-876410482"

shadowsocks_provider: "libev"
shadowsocks_enable_multiport: false #enable multiple port config, only possible for python shadowsocks implementation
shadowsocks_tune_system: true
shadowsocks_change_tcp_congestion_control: false
